kubeProxyReplacement: strict
k8sServiceHost: 10.54.42.101
k8sServicePort: 6443
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
containerRuntime:
  integration: containerd
hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
  relay:
    enabled: true
  ui:
    enabled: true
prometheus:
  enabled: true
operator:
  enabled: true
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  prometheus:
    enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.10.0.0/16